Int_t round(Double_t offset_n )
{
  return floor(offset_n  + 0.5 );
}

void AlignTDC_DM(Char_t* taggfile, Char_t* datafile, Int_t xlow = -50.0, Int_t xhigh = 50.0,Int_t pos = 0.0/*, Int_t switch = 0 */)
{
  // From a detector file find the "Element:" lines and identify the TDCs used
  // for the detector elements. Find the peak position and write this in as TDC offset
  // in a new file copied from the original
  //
  //Adapted from the original macro of JRMA by DM 6/10/2010 v1.0
  //Latest version to use pdf and root file out made 10/02/2014 v1.1
  //
  string temp = taggfile;
  FILE* tfile;                                        // original file pointer
  FILE* mfile;                                        // copy file pointer
  Char_t taggmod[128];                                // new file to create
  Char_t line[256];                                   // input line from file
  Char_t desc[32];                                    // general purpose char string
  Char_t* p[16];                                      // parameters read from line
  for(Int_t i=0; i<16; i++) p[i] = new Char_t[16];

  int uapos = temp.find(".ua");
  if(uapos!=-1){
    temp.replace(uapos,3,"");
  }
  else if(uapos==-1){
    int dpos = temp.find(".dat");
    if(dpos!=-1){
      temp.replace(dpos,4,".alligned.dat");
    }
    else{
      temp.append(".alligned");
    }
  }
  strcpy(taggmod,temp.c_str());

  // Open original and copy files
  printf("Aligning TDC spectra found in  %s\n",taggfile);
  if( (tfile = fopen(taggfile,"r")) == NULL ){        // open original read only
    printf("File %s open failed\n",taggfile);
    return;
  }

  if( (mfile = fopen(taggmod,"w")) == NULL ){         // open copy file for write
    printf("File %s open failed\n",taggmod);
    return;
  }

  sprintf(datafile,"%s",datafile);
  printf("Opening %s for histograms\n",datafile);    //Added so histogram file can be defined
  TFile* data = new TFile(datafile);
  if( !datafile ){ 
    printf("File %s not found\n", datafile);
    return; 
  }

  //Stuff to output a pdf and root file of the fits
  Char_t plotsfile[50];
  strcpy(plotsfile,datafile);
  strcat(plotsfile,".fits.pdf");
  TPDF *pdfout = new TPDF(plotsfile,111);              //define an output pdf plots file
  Int_t pgno=0;
  Char_t pagetitle[100];

  Char_t rootfile[50];
  strcpy(rootfile,datafile);
  strcat(rootfile,".fits.root");
  TFile *rootout = new TFile(rootfile, "RECREATE");    //define an output root histogram file

  TCanvas *canvas = new TCanvas("canvas","Canvas",700,1000);
  canvas->SetFillColor(10);
  canvas->SetBorderSize(2);
  canvas->SetFrameFillColor(10);
  canvas->Divide(4,4);
  Int_t can;                                          //counter to change page

  //Details for the fit function and range.
  TH1F* hist;                                         // TDC spectrum
  Double_t mean;                                      // mean value of TDC spectrum
  Int_t m;
  Float_t offset_i;
  Float_t offset_n;
  Float_t calib;
  TF1 *fit= new TF1("fit","gaus",xlow,xhigh);
  fit->SetLineColor(2);
  Float_t maxbin = 0.0;

  //Start the work

  // Message at top of auto-generated file
  fprintf(mfile,"##  Aligned-TDC AcquRoot Detector file\n");
  fprintf(mfile,"##  Generated by macro DM_AlignTDC.C, D.M. 06/10/2010\n");
  fprintf(mfile,"##  Adapted from the file AlignTDC.C by  J.R.M. Annand\n");
  fprintf(mfile,"##  Alignment made using data file %s,\n",datafile);

  // Read lines from original until EOF
  while( fgets( line, 256, tfile ) ){
    sscanf( line, "%s", desc );                      // get line descriptor
    if( !strcmp( desc, "Element:") ){                // and check if its an element line
      Int_t n = sscanf( line,"%*s%s%s%s%s%s%s%s%s",p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7]);
      n += sscanf( line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%s%s%s%s%s%s%s%s",
		   p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
      if( n != 16){
	printf("Bad file format\n%s\n",line);
	return;
      }

      sprintf(desc,"FPD_Time%d;1",m); // pull out the TDC spec
      m++;

      if(can==0){
	if(pgno>0)
	  pdfout->NewPage();
	
	sprintf(pagetitle,"Tagger Section %c",pgno+65);
	pdfout->SetTitle(pagetitle);

	pgno++;
      }

      can+=1;
      canvas->cd(can);

      hist = (TH1F*)data->Get(desc);        // and search for the TDC histogram
      if( !hist ){
	printf( "%s not found\n", desc );
	return;
      }

      sscanf(line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%f",&offset_i);
      if(!offset_i){
	offset_i = -2000.0;
      }

      sscanf(line,"%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%f",&calib);
      if(!calib){
	calib = 0.1170;
      }

      fit->SetParameter(1,0); //clear this in case there is no data for a fit
      hist->Fit("fit","QR");

      //Get the mean and then convert it to a channel offset
      mean = fit->GetParameter(1);
      if (mean!=0)offset_n = offset_i + ((mean - pos)/calib);
      else offset_n = offset_i;

      offset_n = round(offset_n);

      //Draw the histograms
      hist->SetAxisRange(xlow, xhigh);
      hist->SetTitle("");
      hist->SetXTitle("Time [ns]");
      hist->SetYTitle("Counts");
      hist->Draw();
      hist->Write();

      if(can%16==0){
	canvas->cd();
	canvas->Update();
	can=0;
      }

      //Write the information to the new file

      sprintf( p[8],"%d",offset_n);
      printf("Mean channel of %s is %f and offset is %d\n",desc,mean,offset_n); // progress message
      fprintf(mfile,"%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s\n", "Element:",
	      p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],
	      p[8],p[9],p[10],p[11],p[12],p[13],p[14],p[15] );
    }
    else fputs( line, mfile );    // if not an element line copy it to new file
  }
  // delete any allocated memory and close input and output files 
  for(Int_t i=0; i<16; i++) {delete p[i]};  
  fclose(tfile);
  fclose(mfile);
  data->Close();

  pdfout->Close();
  rootout->Close();

  delete canvas;
  delete pdfout;
  delete rootout;

  return;
}
